# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
LABEL io.openshift.expose-services=8080/tcp:http
RUN chgrp -R 0 /var/log/httpd /run/httpd && chmod -R g=u /var/log/httpd /run/httpd && \
sed -ie "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf
EXPOSE 8080
USER 1001

